{% set name = "bigtree" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kayjan/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 94fbcf07d6c40e65f835da422bfa1bd73581de315c8feb96f9ca17dc284eb6dc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - bigtree
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/kayjan/bigtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tree Implementation and Methods for Python, integrated with list, dictionary, pandas and polars DataFrame.
  doc_url: https://bigtree.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kayjan
