{% set name = "bigtree" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kayjan/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: d46bc901794869f096b1363e5ff3c4b8603928df9001b4ba3feb4210b6bf751b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - bigtree
  requires:
    - pip
    - pytest

about:
  home: https://github.com/kayjan/bigtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tree Implementation and Methods for Python, integrated with Python list, dictionary, and pandas DataFrame.
  doc_url: https://bigtree.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kayjan
