{% set name = "bigtree" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kayjan/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7bc8f3b538789bf8ff1e7774dd6704e305e1c9e19844a0984946eb216a3bef8a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - bigtree
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/kayjan/bigtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tree Implementation and Methods for Python, integrated with list, dictionary, pandas and polars DataFrame.
  doc_url: https://bigtree.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kayjan
