{% set name = "bigtree" %}
{% set version = "0.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kayjan/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ae5250f60970c66d2ad27cd1f6526fa5fdbea0419c828eeb0227c4a5ec86f096

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8

test:
  imports:
    - bigtree
  requires:
    - pip
    - pytest

about:
  home: https://github.com/kayjan/bigtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tree Implementation and Methods for Python, integrated with list, dictionary, pandas and polars DataFrame.
  doc_url: https://bigtree.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kayjan
