{% set name = "bigtree" %}
{% set version = "0.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kayjan/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: d4b0fcef9ba4eb56375c46b6ddab1f5b162deb230d467fda2362673a184c958e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - bigtree
  requires:
    - pip
    - pytest

about:
  home: https://github.com/kayjan/bigtree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tree Implementation and Methods for Python, integrated with list, dictionary, pandas and polars DataFrame.
  doc_url: https://bigtree.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kayjan
